import mongoose from "mongoose";
import dotenv from "dotenv";
import Product from "./models/Product.js";
import Order from "./models/Order.js";

dotenv.config();

const MONGO_URI =
  process.env.MONGO_URI || "mongodb://127.0.0.1:27017/ecommerce";

const img = (url) => ({ url });

const seed = async () => {
  try {
    await mongoose.connect(MONGO_URI);
    console.log("✅ MongoDB connected");

    await Product.deleteMany({});
    await Order.deleteMany({});

    const products = await Product.insertMany([
      // ================= MEN =================
      {
        title: "Men Premium Cotton Shirt",
        slug: "men-premium-cotton-shirt",
        description:
          "Premium cotton shirt designed for a sharp casual and semi-formal look. Soft breathable fabric, clean stitching, and elegant everyday comfort.",
        shortDescription: "Premium cotton shirt with breathable comfort.",
        images: [
          img("https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=900"),
          img("https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=900"),
          img("https://images.unsplash.com/photo-1621072156002-e2fccdc0b176?w=900"),
          img("https://images.unsplash.com/photo-1603252109303-2751441dd157?w=900"),
        ],
        price: 1499,
        original_price: 2199,
        discount_percentage: 32,
        category: "Men",
        gender: "Men",
        brand: "Zara",
        material: "Premium Cotton",
        fit: "Slim Fit",
        color: "White",
        tags: "cotton, formal, office, premium",
        isTrending: true,
        featured: true,
        rating: 4.4,
        stock: 25,
      },
      {
        title: "Men Denim Jacket",
        slug: "men-denim-jacket",
        description:
          "Stylish denim jacket crafted with durable fabric and modern fit. Perfect for layering with tees, shirts, and streetwear outfits.",
        shortDescription: "Modern denim jacket with durable premium stitching.",
        images: [
          img("https://images.unsplash.com/photo-1523205771623-e0faa4d2813d?w=900"),
          img("https://images.unsplash.com/photo-1516257984-b1b4d707412e?w=900"),
          img("https://images.unsplash.com/photo-1520975954732-35dd22299614?w=900"),
          img("https://images.unsplash.com/photo-1611312449408-fcece27cdbb7?w=900"),
        ],
        price: 2499,
        original_price: 3499,
        discount_percentage: 29,
        category: "Men",
        gender: "Men",
        brand: "Levis",
        material: "Denim",
        fit: "Regular Fit",
        color: "Blue",
        tags: "denim, jacket, casual, bestseller",
        isTrending: false,
        featured: true,
        rating: 4.2,
        stock: 10,
      },
      {
        title: "Men Luxury Black Blazer",
        slug: "men-luxury-black-blazer",
        description:
          "Premium black blazer with structured shoulders and refined finish. Ideal for parties, formal events, and luxury styling.",
        shortDescription: "Luxury black blazer for premium formal styling.",
        images: [
          img("https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=900"),
          img("https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=900"),
          img("https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=900"),
          img("https://images.unsplash.com/photo-1520975661595-6453be3f7070?w=900"),
        ],
        price: 3999,
        original_price: 5499,
        discount_percentage: 27,
        category: "Men",
        gender: "Men",
        brand: "Raymond",
        material: "Poly Viscose",
        fit: "Tailored Fit",
        color: "Black",
        tags: "blazer, formal, luxury, party",
        isTrending: true,
        featured: true,
        rating: 4.6,
        stock: 15,
      },
      {
        title: "Men Casual Polo T-Shirt",
        slug: "men-casual-polo-tshirt",
        description:
          "Classic polo t-shirt with soft fabric and clean collar detailing. Made for casual comfort and everyday premium wear.",
        shortDescription: "Classic polo t-shirt with premium soft fabric.",
        images: [
          img("https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=900"),
          img("https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=900"),
          img("https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=900"),
          img("https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=900"),
        ],
        price: 999,
        original_price: 1599,
        discount_percentage: 38,
        category: "Men",
        gender: "Men",
        brand: "H&M",
        material: "Cotton Blend",
        fit: "Regular Fit",
        color: "Navy Blue",
        tags: "polo, casual, cotton, dailywear",
        isTrending: false,
        featured: false,
        rating: 4.1,
        stock: 28,
      },

      // ================= WOMEN =================
      {
        title: "Women Floral Summer Dress",
        slug: "women-floral-summer-dress",
        description:
          "Elegant floral summer dress made with soft breathable fabric and premium finish. Perfect for brunch, vacations, and casual outings.",
        shortDescription: "Soft floral summer dress with elegant styling.",
        images: [
          img("https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=900"),
          img("https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=900"),
          img("https://images.unsplash.com/photo-1485968579580-b6d095142e6e?w=900"),
          img("https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=900"),
        ],
        price: 2199,
        original_price: 2999,
        discount_percentage: 27,
        category: "Women",
        gender: "Women",
        brand: "H&M",
        material: "Cotton Blend",
        fit: "Regular Fit",
        color: "White",
        tags: "summer, floral, dress, trending",
        isTrending: true,
        featured: true,
        rating: 4.3,
        stock: 18,
      },
      {
        title: "Women Ethnic Kurti",
        slug: "women-ethnic-kurti",
        description:
          "Beautiful ethnic kurti with elegant print and soft fabric. Perfect for daily wear, office wear, and festive styling.",
        shortDescription: "Elegant ethnic kurti with soft premium fabric.",
        images: [
          img("https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=900"),
          img("https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=900"),
          img("https://images.unsplash.com/photo-1609357605129-26f69add5d6e?w=900"),
          img("https://images.unsplash.com/photo-1594739033447-80ab21e24b4c?w=900"),
        ],
        price: 1299,
        original_price: 1999,
        discount_percentage: 35,
        category: "Women",
        gender: "Women",
        brand: "Biba",
        material: "Rayon",
        fit: "Straight Fit",
        color: "Purple",
        tags: "kurti, ethnic, festive, women",
        isTrending: true,
        featured: false,
        rating: 4.5,
        stock: 22,
      },
      {
        title: "Women Satin Party Gown",
        slug: "women-satin-party-gown",
        description:
          "Premium satin party gown with graceful fall and luxury finish. Designed for evening parties, celebrations, and special occasions.",
        shortDescription: "Luxury satin gown for evening party styling.",
        images: [
          img("https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=900"),
          img("https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=900"),
          img("https://images.unsplash.com/photo-1509631179647-0177331693ae?w=900"),
          img("https://images.unsplash.com/photo-1483985988355-763728e1935b?w=900"),
        ],
        price: 3499,
        original_price: 4999,
        discount_percentage: 30,
        category: "Women",
        gender: "Women",
        brand: "Zara",
        material: "Satin",
        fit: "A-Line Fit",
        color: "Black",
        tags: "gown, party, satin, luxury",
        isTrending: false,
        featured: true,
        rating: 4.4,
        stock: 14,
      },
      {
        title: "Women Premium Denim Jeans",
        slug: "women-premium-denim-jeans",
        description:
          "High-rise premium denim jeans with comfortable stretch and modern fit. Perfect for everyday casual and streetwear styling.",
        shortDescription: "High-rise denim jeans with stretch comfort.",
        images: [
          img("https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=900"),
          img("https://images.unsplash.com/photo-1582418702059-97ebafb35d09?w=900"),
          img("https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=900"),
          img("https://images.unsplash.com/photo-1475180098004-ca77a66827be?w=900"),
        ],
        price: 1899,
        original_price: 2599,
        discount_percentage: 27,
        category: "Women",
        gender: "Women",
        brand: "Levis",
        material: "Stretch Denim",
        fit: "High-Rise Fit",
        color: "Blue",
        tags: "jeans, denim, casual, women",
        isTrending: false,
        featured: false,
        rating: 4.2,
        stock: 20,
      },

      // ================= KIDS =================
      {
        title: "Kids Printed T-Shirt",
        slug: "kids-printed-tshirt",
        description:
          "Comfortable and colorful printed t-shirt for kids. Soft cotton fabric keeps children comfortable all day long.",
        shortDescription: "Soft printed cotton t-shirt for kids.",
        images: [
          img("https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=900"),
          img("https://images.unsplash.com/photo-1514090458221-65bb69cf63e6?w=900"),
          img("https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=900"),
          img("https://images.unsplash.com/photo-1542037104857-ffbb0b9155fb?w=900"),
        ],
        price: 799,
        original_price: 1199,
        discount_percentage: 33,
        category: "Kids",
        gender: "Kids",
        brand: "MiniClub",
        material: "Soft Cotton",
        fit: "Regular Fit",
        color: "Yellow",
        tags: "kids, tshirt, cotton, printed",
        isTrending: false,
        featured: true,
        rating: 4.1,
        stock: 30,
      },
      {
        title: "Kids Party Wear Dress",
        slug: "kids-party-wear-dress",
        description:
          "Cute party wear dress for kids with premium comfortable fabric and elegant design for birthdays and celebrations.",
        shortDescription: "Cute party dress with premium comfort.",
        images: [
          img("https://images.unsplash.com/photo-1514090458221-65bb69cf63e6?w=900"),
          img("https://images.unsplash.com/photo-1522771930-78848d9293e8?w=900"),
          img("https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=900"),
          img("https://images.unsplash.com/photo-1542037104857-ffbb0b9155fb?w=900"),
        ],
        price: 1599,
        original_price: 2299,
        discount_percentage: 30,
        category: "Kids",
        gender: "Kids",
        brand: "Babyhug",
        material: "Net Blend",
        fit: "Comfort Fit",
        color: "Pink",
        tags: "kids, partywear, dress, celebration",
        isTrending: true,
        featured: false,
        rating: 4.4,
        stock: 16,
      },
      
      {
        title: "Kids Winter Hoodie",
        slug: "kids-winter-hoodie",
        description:
          "Warm and cozy hoodie for kids with soft fleece lining. Designed for winter comfort and cute casual styling.",
        shortDescription: "Warm fleece hoodie for winter comfort.",
        images: [
          img("https://images.unsplash.com/photo-1542037104857-ffbb0b9155fb?w=900"),
          img("https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=900"),
          img("https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=900"),
          img("https://images.unsplash.com/photo-1522771930-78848d9293e8?w=900"),
        ],
        price: 1199,
        original_price: 1799,
        discount_percentage: 33,
        category: "Kids",
        gender: "Kids",
        brand: "Max",
        material: "Fleece Cotton",
        fit: "Regular Fit",
        color: "Grey",
        tags: "kids, hoodie, winter, fleece",
        isTrending: false,
        featured: false,
        rating: 4.0,
        stock: 24,
      },

      // ================= FOOTWEAR =================
      {
        title: "Nike Running Sneakers",
        slug: "nike-running-sneakers",
        description:
          "Lightweight running sneakers with cushioned sole and breathable mesh design for comfort during workouts and daily wear.",
        shortDescription: "Lightweight sneakers with cushioned comfort.",
        images: [
          img("https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=900"),
          img("https://images.unsplash.com/photo-1549298916-b41d501d3772?w=900"),
          img("https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=900"),
          img("https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=900"),
        ],
        price: 3499,
        original_price: 4999,
        discount_percentage: 30,
        category: "Footwear",
        gender: "Unisex",
        brand: "Nike",
        material: "Mesh",
        fit: "Comfort Fit",
        color: "Red",
        tags: "sneakers, running, shoes, sports",
        isTrending: true,
        featured: true,
        rating: 4.6,
        stock: 20,
      },
      {
        title: "Adidas Casual Shoes",
        slug: "adidas-casual-shoes",
        description:
          "Trendy casual shoes with stylish design and comfortable sole. Perfect for college, casual outings, and daily wear.",
        shortDescription: "Trendy casual shoes with comfort sole.",
        images: [
          img("https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=900"),
          img("https://images.unsplash.com/photo-1549298916-b41d501d3772?w=900"),
          img("https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=900"),
          img("https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=900"),
        ],
        price: 2999,
        original_price: 4299,
        discount_percentage: 30,
        category: "Footwear",
        gender: "Unisex",
        brand: "Adidas",
        material: "Synthetic",
        fit: "Regular Fit",
        color: "White",
        tags: "casual, shoes, sneakers, dailywear",
        isTrending: false,
        featured: true,
        rating: 4.3,
        stock: 14,
      },
      {
        title: "Puma Streetwear Sneakers",
        slug: "puma-streetwear-sneakers",
        description:
          "Premium streetwear sneakers with bold design and soft footbed for everyday comfort and standout styling.",
        shortDescription: "Streetwear sneakers with bold premium design.",
        images: [
          img("https://images.unsplash.com/photo-1543508282-6319a3e2621f?w=900"),
          img("https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=900"),
          img("https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=900"),
          img("https://images.unsplash.com/photo-1552346154-21d32810aba3?w=900"),
        ],
        price: 3299,
        original_price: 4599,
        discount_percentage: 28,
        category: "Footwear",
        gender: "Unisex",
        brand: "Puma",
        material: "Synthetic Leather",
        fit: "Comfort Fit",
        color: "Black",
        tags: "puma, sneakers, streetwear, premium",
        isTrending: true,
        featured: false,
        rating: 4.4,
        stock: 17,
      },
      {
        title: "Women Beige Heels",
        slug: "women-beige-heels",
        description:
          "Elegant beige heels with premium finish and comfortable sole. Perfect for parties, office wear, and festive looks.",
        shortDescription: "Elegant beige heels with premium finish.",
        images: [
          img("https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=900"),
          img("https://images.unsplash.com/photo-1515347619252-60a4bf4fff4f?w=900"),
          img("https://images.unsplash.com/photo-1562273138-f46be4ebdf33?w=900"),
          img("https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=900"),
        ],
        price: 2299,
        original_price: 3199,
        discount_percentage: 28,
        category: "Footwear",
        gender: "Women",
        brand: "Metro",
        material: "Faux Leather",
        fit: "Comfort Fit",
        color: "Beige",
        tags: "heels, women, party, footwear",
        isTrending: false,
        featured: false,
        rating: 4.2,
        stock: 12,
      },

      // ================= ACCESSORIES =================
      {
        title: "Leather Handbag",
        slug: "leather-handbag",
        description:
          "Premium leather handbag with spacious compartments, luxury finish, and elegant design for daily and occasion styling.",
        shortDescription: "Luxury handbag with spacious compartments.",
        images: [
          img("https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=900"),
          img("https://images.unsplash.com/photo-1594223274512-ad4803739b7c?w=900"),
          img("https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=900"),
          img("https://images.unsplash.com/photo-1585488433867-c76d8c8b96d5?w=900"),
        ],
        price: 2799,
        original_price: 3999,
        discount_percentage: 30,
        category: "Accessories",
        gender: "Women",
        brand: "Lavie",
        material: "Faux Leather",
        fit: "Medium Size",
        color: "Red",
        tags: "handbag, luxury, accessories, women",
        isTrending: false,
        featured: true,
        rating: 4.5,
        stock: 12,
      },
      {
        title: "Gold Plated Bracelet",
        slug: "gold-plated-bracelet",
        description:
          "Elegant gold plated bracelet crafted for a premium fashion look. Perfect for gifting, festive looks, and daily elegance.",
        shortDescription: "Elegant gold plated bracelet for premium styling.",
        images: [
          img("https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=900"),
          img("https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=900"),
          img("https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=900"),
          img("https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=900"),
        ],
        price: 999,
        original_price: 1499,
        discount_percentage: 33,
        category: "Accessories",
        gender: "Women",
        brand: "Voylla",
        material: "Gold Plated Alloy",
        fit: "Adjustable",
        color: "Gold",
        tags: "bracelet, jewelry, gold, trending",
        isTrending: true,
        featured: true,
        rating: 4.4,
        stock: 35,
      },
      {
        title: "Luxury Analog Watch",
        slug: "luxury-analog-watch",
        description:
          "Premium analog watch with classic dial and luxury strap. Designed for formal, casual, and gifting occasions.",
        shortDescription: "Classic analog watch with premium finish.",
        images: [
          img("https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=900"),
          img("https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=900"),
          img("https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=900"),
          img("https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=900"),
        ],
        price: 1999,
        original_price: 2999,
        discount_percentage: 33,
        category: "Accessories",
        gender: "Unisex",
        brand: "Fossil",
        material: "Stainless Steel",
        fit: "Adjustable Strap",
        color: "Brown",
        tags: "watch, luxury, accessories, gifting",
        isTrending: false,
        featured: true,
        rating: 4.3,
        stock: 18,
      },
      {
        title: "Premium Sunglasses",
        slug: "premium-sunglasses",
        description:
          "Premium sunglasses with UV protection and elegant frame design. Perfect for travel, streetwear, and luxury casual styling.",
        shortDescription: "UV-protected sunglasses with elegant frame.",
        images: [
          img("https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=900"),
          img("https://images.unsplash.com/photo-1508296695146-257a814070b4?w=900"),
          img("https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=900"),
          img("https://images.unsplash.com/photo-1556306535-38febf6782e7?w=900"),
        ],
        price: 1299,
        original_price: 1999,
        discount_percentage: 35,
        category: "Accessories",
        gender: "Unisex",
        brand: "Ray-Ban",
        material: "Acetate Frame",
        fit: "Regular Fit",
        color: "Black",
        tags: "sunglasses, travel, accessories, premium",
        isTrending: true,
        featured: false,
        rating: 4.2,
        stock: 21,
      },
    ]);

    console.log(`📦 Inserted ${products.length} products`);

    const now = new Date();

    const orders = [
      {
        user: new mongoose.Types.ObjectId(),
        items: [
          {
            product: products[0]._id,
            title: products[0].title,
            price: products[0].price,
            quantity: 2,
          },
        ],
        total: products[0].price * 2,
        status: "delivered",
        createdAt: new Date(new Date().setMonth(now.getMonth() - 5)),
      },
      {
        user: new mongoose.Types.ObjectId(),
        items: [
          {
            product: products[4]._id,
            title: products[4].title,
            price: products[4].price,
            quantity: 1,
          },
        ],
        total: products[4].price,
        status: "processing",
        createdAt: new Date(new Date().setMonth(now.getMonth() - 4)),
      },
      {
        user: new mongoose.Types.ObjectId(),
        items: [
          {
            product: products[12]._id,
            title: products[12].title,
            price: products[12].price,
            quantity: 1,
          },
        ],
        total: products[12].price,
        status: "pending",
        createdAt: new Date(new Date().setMonth(now.getMonth() - 2)),
      },
      {
        user: new mongoose.Types.ObjectId(),
        items: [
          {
            product: products[16]._id,
            title: products[16].title,
            price: products[16].price,
            quantity: 2,
          },
        ],
        total: products[16].price * 2,
        status: "shipped",
        createdAt: new Date(),
      },
    ];

    await Order.insertMany(orders);

    console.log(`🧾 Inserted ${orders.length} orders`);
    console.log("✅ Fashion e-commerce seeding completed!");

    process.exit();
  } catch (err) {
    console.error("❌ Seeding error:", err);
    process.exit(1);
  }
};

seed();